name: Restart Eleventy container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull code and restart container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: ~/update-blog.sh
  # build:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [21.x]

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     - name: Install dependencies & build
  #       run: |
  #         npm ci
  #         npm run build          

  #     - name: Deploy
  #       uses: peaceiris/actions-gh-pages@v4
  #       with:
  #         publish_dir: ./_site
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  