name: Eleventy Build


on:
  push:
    branches:
      - 11ty
      
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@11ty
      - name: Build
        uses: TartanLlama/actions-eleventy@11ty
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}